site_name: DISP
theme:
  name: material
nav:
  - Home: "index.md"
  - Getting Started: 
    - Installation: "Getting Started/installation.md"
    - Tutorial: 
      - Lennard-Jones Solid: "examples/1.1/README.md"
  - Background:
    - Crystal Structure Prediction: "background/structure_searching.md"
    - AIRSS: "background/airss.md"
    - Workflow Engine: "background/workflow_engine.md"
  - AIRSS Guide:
    - Introduction: "AIRSS Guide/introduction.md"
    - Inputs: "AIRSS Guide/inputs.md"
    - castep_relax: "AIRSS Guide/castep_relax.md"

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js