# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.3.0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]

    - name: Install AIRSS
      run: |
        sudo apt-get install gfortran liblapack-dev
        wget -O airss-0.9.1.tar.gz https://www.dropbox.com/s/rdyq8df2kr8k77b/airss-0.9.1.tar.gz?dl=1
        tar zxf airss-0.9.1.tar.gz
        cd airss-0.9.1/
        make buildcell
        make cabal
        make cryan
        make pp3
        cp src/buildcell/src/buildcell bin/
        cp src/cryan/src/cryan bin/
        cp src/cabal/src/cabal bin/
        cp src/pp3/src/pp3 bin/
        cd ../

    - name: Test with pytest
      run: |
        export PATH=`pwd`/airss-0.9.1/bin:$PATH
        which buildcell
        pytest
